import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Simple PDF generation for receipts (stored as text-based PDF)
function generateReceiptContent(data: {
  tnxId: string;
  memberName: string;
  accountNumber: string;
  transactionType: string;
  amount: number;
  balanceAfter: number;
  currentBalance: number;
  totalSavings: number;
  description?: string;
  createdAt: string;
  approvedAt?: string;
}): string {
  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  // Create a simple text-based receipt that can be stored and displayed
  return `
================================================================================
                              KINONI SACCO
                          TRANSACTION RECEIPT
================================================================================

Transaction ID: ${data.tnxId}
Date: ${formatDate(data.createdAt)}

--------------------------------------------------------------------------------
MEMBER DETAILS
--------------------------------------------------------------------------------
Member Name:     ${data.memberName}
Account Number:  ${data.accountNumber}

--------------------------------------------------------------------------------
TRANSACTION DETAILS
--------------------------------------------------------------------------------
Type:            ${data.transactionType.replace('_', ' ').toUpperCase()}
Amount:          UGX ${data.amount.toLocaleString()}
${data.description ? `Description:     ${data.description}` : ''}

--------------------------------------------------------------------------------
ACCOUNT BALANCES (UPDATED)
--------------------------------------------------------------------------------
Balance After Transaction:  UGX ${data.balanceAfter.toLocaleString()}
Current Account Balance:    UGX ${data.currentBalance.toLocaleString()}
Total Savings:              UGX ${data.totalSavings.toLocaleString()}

--------------------------------------------------------------------------------
STATUS: APPROVED
${data.approvedAt ? `Approved On: ${formatDate(data.approvedAt)}` : ''}
--------------------------------------------------------------------------------

This receipt is generated by KINONI SACCO Management System.
Keep this receipt for your records.

================================================================================
`;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    )

    const { transactionId, generateAll } = await req.json()

    console.log('Generate receipt request:', { transactionId, generateAll })

    if (generateAll) {
      // Generate receipts for all approved transactions without receipts
      const { data: transactions, error: txError } = await supabaseAdmin
        .from('transactions')
        .select(`
          id,
          tnx_id,
          transaction_type,
          amount,
          balance_after,
          description,
          created_at,
          approved_at,
          status,
          account_id,
          accounts!inner (
            id,
            account_number,
            user_id,
            account_type,
            parent_account_id
          )
        `)
        .eq('status', 'approved')

      if (txError) {
        console.error('Error fetching transactions:', txError)
        return new Response(
          JSON.stringify({ error: txError.message }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
      }

      if (!transactions || transactions.length === 0) {
        return new Response(
          JSON.stringify({ message: 'No approved transactions found', generated: 0 }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
      }

      let generated = 0
      let errors = 0

      for (const tx of transactions) {
        try {
          const account = tx.accounts as any
          
          // Check if receipt already exists
          const { data: existingReceipt } = await supabaseAdmin.storage
            .from('receipts')
            .list('', { search: `receipt_${tx.tnx_id}` })
          
          if (existingReceipt && existingReceipt.length > 0) {
            console.log(`Receipt already exists for ${tx.tnx_id}, skipping`)
            continue
          }

          // Get current account balance and total savings
          const { data: currentAccountData } = await supabaseAdmin
            .from('accounts')
            .select('balance, total_savings')
            .eq('id', account.id)
            .single()

          // Get member name
          let memberName = 'Unknown'
          
          if (account.account_type === 'sub') {
            const { data: subProfile } = await supabaseAdmin
              .from('sub_account_profiles')
              .select('full_name')
              .eq('account_id', account.id)
              .single()
            memberName = subProfile?.full_name || 'Unknown'
          } else {
            const { data: profile } = await supabaseAdmin
              .from('profiles')
              .select('full_name')
              .eq('id', account.user_id)
              .single()
            memberName = profile?.full_name || 'Unknown'
          }

          const receiptContent = generateReceiptContent({
            tnxId: tx.tnx_id,
            memberName,
            accountNumber: account.account_number,
            transactionType: tx.transaction_type,
            amount: tx.amount,
            balanceAfter: tx.balance_after,
            currentBalance: currentAccountData?.balance || tx.balance_after,
            totalSavings: currentAccountData?.total_savings || 0,
            description: tx.description,
            createdAt: tx.created_at,
            approvedAt: tx.approved_at,
          })

          // Upload to storage
          const fileName = `receipt_${tx.tnx_id}.txt`
          const { error: uploadError } = await supabaseAdmin.storage
            .from('receipts')
            .upload(fileName, receiptContent, {
              contentType: 'text/plain',
              upsert: true
            })

          if (uploadError) {
            console.error(`Error uploading receipt for ${tx.tnx_id}:`, uploadError)
            errors++
          } else {
            console.log(`Generated receipt for ${tx.tnx_id}`)
            generated++
          }
        } catch (err) {
          console.error(`Error processing transaction ${tx.id}:`, err)
          errors++
        }
      }

      return new Response(
        JSON.stringify({ message: `Generated ${generated} receipts`, generated, errors }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Generate receipt for a single transaction
    if (!transactionId) {
      return new Response(
        JSON.stringify({ error: 'Transaction ID is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { data: tx, error: txError } = await supabaseAdmin
      .from('transactions')
      .select(`
        id,
        tnx_id,
        transaction_type,
        amount,
        balance_after,
        description,
        created_at,
        approved_at,
        status,
        account_id,
        accounts!inner (
          id,
          account_number,
          user_id,
          account_type,
          parent_account_id
        )
      `)
      .eq('id', transactionId)
      .single()

    if (txError || !tx) {
      console.error('Transaction not found:', txError)
      return new Response(
        JSON.stringify({ error: 'Transaction not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const account = tx.accounts as any

    // Get current account balance and total savings
    const { data: currentAccountData } = await supabaseAdmin
      .from('accounts')
      .select('balance, total_savings')
      .eq('id', account.id)
      .single()

    // Get member name
    let memberName = 'Unknown'
    
    if (account.account_type === 'sub') {
      const { data: subProfile } = await supabaseAdmin
        .from('sub_account_profiles')
        .select('full_name')
        .eq('account_id', account.id)
        .single()
      memberName = subProfile?.full_name || 'Unknown'
    } else {
      const { data: profile } = await supabaseAdmin
        .from('profiles')
        .select('full_name')
        .eq('id', account.user_id)
        .single()
      memberName = profile?.full_name || 'Unknown'
    }

    const receiptContent = generateReceiptContent({
      tnxId: tx.tnx_id,
      memberName,
      accountNumber: account.account_number,
      transactionType: tx.transaction_type,
      amount: tx.amount,
      balanceAfter: tx.balance_after,
      currentBalance: currentAccountData?.balance || tx.balance_after,
      totalSavings: currentAccountData?.total_savings || 0,
      description: tx.description,
      createdAt: tx.created_at,
      approvedAt: tx.approved_at,
    })

    // Upload to storage
    const fileName = `receipt_${tx.tnx_id}.txt`
    const { error: uploadError } = await supabaseAdmin.storage
      .from('receipts')
      .upload(fileName, receiptContent, {
        contentType: 'text/plain',
        upsert: true
      })

    if (uploadError) {
      console.error('Error uploading receipt:', uploadError)
      return new Response(
        JSON.stringify({ error: uploadError.message }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Get public URL
    const { data: urlData } = supabaseAdmin.storage
      .from('receipts')
      .getPublicUrl(fileName)

    console.log('Receipt generated successfully:', fileName)

    return new Response(
      JSON.stringify({ 
        success: true, 
        receiptUrl: urlData.publicUrl,
        fileName 
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error in generate-receipt function:', error)
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred'
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
